export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const LOAD_EVENTS_ERROR = 'LOAD_EVENTS_ERROR';
export const GET_CURRENT_GEOLOCATION = 'GET_CURRENT_GEOLOCATION';
export const GET_EVENT_BY_ID = 'GET_EVENT_BY_ID';
export const SEARCH_EVENTS_SUCCESS = 'SEARCH_EVENTS_SUCCESS';
